### ISSUE TITLE
Monitoring Kubernetes PVs

### ISSUE THREAD

**Issue by 2phost** [linode/linode-blockstorage-csi-driver#62]
## Feature Request

I expected to be able to see PV stats, like diskspace free etc.  I am already scraping kubelet metrics,  however I didn't find any metrics named kubelet_volume_stats_* .

From my undestanding CSI driver is responsible for providing metrics. Specifically, the endpoint [NodeGetVolumeStats](https://github.com/container-storage-interface/spec/blob/4731db0e0bc53238b93850f43ab05d9355df0fd9/spec.md#nodegetvolumestats) is supposed to provide metrics around disk and inode capacity.

Searched around, and it looks like other providers were able to implement this, such as:
https://github.com/digitalocean/csi-digitalocean/issues/134
https://github.com/digitalocean/csi-digitalocean/pull/197

Some references that may help:
https://github.com/container-storage-interface/spec/pull/256
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/223
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/589

**Comment by 2phost** [comment]
I just dig a little further and I found that you already have the placeholder of the implementation:
https://github.com/linode/linode-blockstorage-csi-driver/blob/ea5a2378232095e1fd65dd8a3af56cebd823ebc5/pkg/linode-bs/nodeserver.go#L306

**Comment by LuminousPath** [comment]
+1 on this, would be very useful for Database PV's

**Comment by jb3** [comment]
Another +1 on this, we had a couple of incidents just this week where Prometheus filled it's disk space and due to the lack of metrics we weren't alerted until Prometheus started receiving disk filled errors. Being able to pull volume metrics into Prometheus and similar tools would be hugely powerful.

**Comment by igorbrigadir** [comment]
It's been a while, just wondering if this is on the radar for future development too?

**Comment by lotus-x** [comment]
Any progress on this?

**Comment by beegmon** [comment]
+1 here as we really need a clean way to monitor volumes usage and free space

**Comment by ajguyot** [comment]
+1 here.

Does anybody know of a workaround to get PV metrics in the meantime, since the Linode team has been ignoring this issue for years now (unclear if the acquisition will help or hurt this...)? Is it just not possible unless legitimate support is added?

**Comment by jilleJr** [comment]
@ajguyot Yes one workaround I've been using is to do my own scraping via a script that basically runs `df` every now and then, and then exports this via nginx for prometheus to scrape:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linode-volume-exporter
  namespace: kube-system
  labels:
    k8s-app: linode-volume-exporter
spec:
  selector:
    matchLabels:
      name: linode-volume-exporter
  template:
    metadata:
      labels:
        name: linode-volume-exporter
      annotations:
        prometheus.io/path: /metrics.txt
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: scraper
        image: alpine
        command:
          - sh
          - -c
          - |
            set -eu
            : ${OUT_FILE:=/mnt/metrics/metrics.txt}
            : ${NODE_NAME?}
            : ${INTERVAL:=10s}

            trap exit SIGTERM
            
            collect_metrics(){
              df -P | grep 'kubernetes\.io\~csi/[^/]*/mount' | while IFS= read -r line
              do
                DISK_TOTAL="$(echo $line | cut -d' ' -f2)"
                DISK_USED="$(echo $line | cut -d' ' -f3)"
                DISK_AVAIL="$(echo $line | cut -d' ' -f4)"
                MOUNT_PATH="$(echo $line | cut -d' ' -f6)"
                PV_NAME="$(basename "$(dirname "$MOUNT_PATH")")"
                echo "linode_pv_usage_bytes{persistentvolume=\"${PV_NAME}\",node=\"$NODE_NAME\"} $DISK_USED"
                echo "linode_pv_available_bytes{persistentvolume=\"${PV_NAME}\",node=\"$NODE_NAME\"} $DISK_AVAIL"
                echo "linode_pv_total_bytes{persistentvolume=\"${PV_NAME}\",node=\"$NODE_NAME\"} $DISK_TOTAL"
              done
            }
            
            echo "INTERVAL=$INTERVAL"
            echo "OUT_FILE=$OUT_FILE"
            while true
            do
              # cache results in memory
              METRICS="$(collect_metrics)"
              HEADER="# Prometheus metrics for Linode Volumes, generated at $(date)"
              echo "$HEADER" > "$OUT_FILE"
              echo "$METRICS" >> "$OUT_FILE"
              sleep "$INTERVAL"
            done

        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          # We can disable container root access,
          # but the container must run as root to
          # be able to read the volume statuses.
          # Don't need privileged container, though.
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /mnt/host-pods
            name: host-pods
            readOnly: true
          - mountPath: /mnt/metrics
            name: metrics

      - name: exporter
        image: nginx:alpine
        ports:
          - containerPort: 80
            name: scrape
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: metrics
            readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: metrics
          emptyDir: {}
```

It requires having a hostPath volume of all the node's pods mounted into the container, which then `df` finds automatically. This works great on LKE clusters. Have not tested on bare-Linode machines with manually installed Kubernetes.

---

This is based on some code I wrote for the OpenEBS monitor-pv, which is just a glorified script that runs `du` to calculate local-pv disk usage: https://github.com/openebs/monitor-pv/pull/13

But for Linode's volumes, it's much faster as we can make use of `df` instead.

However, would be much nicer if the CSI driver just exported its own metrics.
